[package]
name = "github-types"
version = "0.1.0"
authors = ["Jason White <rust@jasonwhite.io>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
hex = "0.3"
serde = { version = "1", features = ["derive"] }
